name: Run Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 22f3000585@ds.study.iitm.ac.in
        run: echo "Hello, world!"
